name: terraform-lint

on:
  workflow_dispatch:
  
jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
      
    - name: Fmt Terraform
      run: |
       terraform fmt -recursive
      
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main

    - name: tfsec
      uses: tfsec/tfsec-sarif-action@main
      with:
        sarif_file: tfsec.sarif         

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif    
