name: terraform-lint

on:
  workflow_dispatch:
  
jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
      
    - name: Fmt Terraform
      run: |
       terraform fmt -recursive
      
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main
    
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: true
    
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
