name: terraform-lint

on:
  workflow_dispatch:
  
jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
      
    - name: Scrape
      run: |
       terraform fmt -recursive
      
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main
